import { Rule } from '@/types';

export const RULES: Rule[] = [
  {
    id: 'RULE_P2_075',
    subject: 'Main Aisle Clear Width',
    contextLocation: 'Ontario',
    constraintType: 'Minimum',
    value: '1100',
    unit: 'mm',
    buildingType: 'Business / Personal Services / Mercantile',
    sectionReference: 'OFC 2.7.1.2',
    severity: 'Critical',
    confidence: 'High',
    sourceDocument: 'Ontario Fire Code (O. Reg. 213/07)',
    authorityRank: 2,
    appliesToScope: 'Both',
  },
  {
    id: 'RULE_P2_087',
    subject: 'Assembly Aisle Width — Nonfixed Seating',
    contextLocation: 'Ontario',
    constraintType: 'Minimum',
    value: '1100',
    unit: 'mm',
    buildingType: 'Assembly',
    sectionReference: 'OFC 2.7.1.6(3)',
    severity: 'Critical',
    confidence: 'High',
    sourceDocument: 'Ontario Fire Code (O. Reg. 213/07)',
    authorityRank: 2,
    appliesToScope: 'Both',
  },
  {
    id: 'RULE_P6_023',
    subject: 'Portable Extinguisher Inspection',
    contextLocation: 'Ontario',
    constraintType: 'Maximum',
    value: '12',
    unit: 'months',
    buildingType: 'All',
    sectionReference: 'OFC 6.2.7.1',
    severity: 'Major',
    confidence: 'High',
    sourceDocument: 'Ontario Fire Code (O. Reg. 213/07)',
    authorityRank: 2,
    appliesToScope: 'Both',
  },
  {
    id: 'RULE_P2_138',
    subject: 'Smoke Alarm Installation — Dwelling Units',
    contextLocation: 'Ontario',
    constraintType: 'Required',
    value: 'Every dwelling unit',
    unit: '',
    buildingType: 'Residential',
    sectionReference: 'OFC 2.13.1.1',
    severity: 'Critical',
    confidence: 'High',
    sourceDocument: 'Ontario Fire Code (O. Reg. 213/07)',
    authorityRank: 2,
    appliesToScope: 'Both',
  },
  {
    id: 'RULE_P2_127',
    subject: 'Fire Drill Frequency — Care / Detention',
    contextLocation: 'Ontario',
    constraintType: 'Minimum',
    value: 'Monthly',
    unit: 'per month',
    buildingType: 'Care / Detention',
    sectionReference: 'OFC 2.8.3.2(1)(a)',
    severity: 'Critical',
    confidence: 'High',
    sourceDocument: 'Ontario Fire Code (O. Reg. 213/07)',
    authorityRank: 2,
    appliesToScope: 'Both',
  },
];

export function getAllRules(): Rule[] { return RULES; }
export function getRuleById(id: string): Rule | undefined { return RULES.find(r => r.id === id); }
